[package]
name = "alt-updater"
version = "0.1.0"
description = "Address Lookup Table Updater client"
edition = "2021"

[dependencies]
solana-client = "~2.1.21"
solana-sdk = "~2.1.21"
solana-program = "~2.1.21"
tokio = "1.45.1"
