[package]
name = "alt-updater"
version = "0.1.0"
description = "Address Lookup Table Updater program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "~2.1.21"

[features]
custom-heap = []
custom-panic = []
